# docker-compose.yml
version: "3.8"

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=password1234
      - NIFI_WEB_HTTPS_PORT=8443
    volumes:
      - ./nifi-data/input:/opt/nifi/nifi-current/nifi-data/input
      - ./nifi-data/output:/opt/nifi/nifi-current/nifi-data/output
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-database:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content:/opt/nifi/nifi-current/content_repository
      - nifi-provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi-state:/opt/nifi/nifi-current/state
      - nifi-logs:/opt/nifi/nifi-current/logs
    networks:
      - nifi-network
    depends_on:
      - nifi-registry
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8443/nifi"]
      interval: 30s
      timeout: 10s
      retries: 5

  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    ports:
      - "18080:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    volumes:
      - ./registry-data/database:/opt/nifi-registry/nifi-registry-current/database
      - ./registry-data/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
    networks:
      - nifi-network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:18080/nifi-registry-api/buckets",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  nifi-conf:
  nifi-database:
  nifi-flowfile:
  nifi-content:
  nifi-provenance:
  nifi-state:
  nifi-logs:
  nifi-registry-database:
  nifi-registry-flow-storage:
  nifi-registry-logs:

networks:
  nifi-network:
    driver: bridge
